In [40]:
import pandas as pd
import numpy as np 

In [41]:
df = pd.read_csv("../DataSets/BFS_train.csv")
df

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
...         ...        ...    ...    ...         ...           ...   
550063  1006033  P00372445      M  51-55          13             B   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               0                   3   
1                               2               0                   1   
2                               2               0                  12   
3                               2               0                  12   
4                              4+               0                   8   
...                           ...             ...                 ...   
550063                          1               1                  20   
550064                          3               0                  20   
550065                         4+               1                  20   
550066                          2               0                  20   
550067                         4+               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
0                      NaN                 NaN      8370  
1                      6.0                14.0     15200  
2                      NaN                 NaN      1422  
3                     14.0                 NaN      1057  
4                      NaN                 NaN      7969  
...                    ...                 ...       ...  
550063                 NaN                 NaN       368  
550064                 NaN                 NaN       371  
550065                 NaN                 NaN       137  
550066                 NaN                 NaN       365  
550067                 NaN                 NaN       490  

[550068 rows x 12 columns]

In [42]:
df.dtypes

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                        int64
dtype: object

In [43]:
df.isnull().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [44]:
df['Age'].unique()

array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

In [45]:
kd = df['Age'].replace('55+')
kd

0          0-17
1          0-17
2          0-17
3          0-17
4          0-17
          ...  
550063    51-55
550064    26-35
550065    26-35
550066    26-35
550067    46-50
Name: Age, Length: 550068, dtype: object

In [46]:
columns_to_drop = ["User_ID","Product_ID","Gender","Marital_Status","Age","Stay_In_Current_City_Years",
                  "Occupation"]
df= df.drop(columns=columns_to_drop)
df

City_Category  Product_Category_1  Product_Category_2  \
0                  A                   3                 NaN   
1                  A                   1                 6.0   
2                  A                  12                 NaN   
3                  A                  12                14.0   
4                  C                   8                 NaN   
...              ...                 ...                 ...   
550063             B                  20                 NaN   
550064             C                  20                 NaN   
550065             B                  20                 NaN   
550066             C                  20                 NaN   
550067             B                  20                 NaN   

        Product_Category_3  Purchase  
0                      NaN      8370  
1                     14.0     15200  
2                      NaN      1422  
3                      NaN      1057  
4                      NaN      7969  
...                    ...       ...  
550063                 NaN       368  
550064                 NaN       371  
550065                 NaN       137  
550066                 NaN       365  
550067                 NaN       490  

[550068 rows x 5 columns]

In [47]:
df.dtypes

City_Category          object
Product_Category_1      int64
Product_Category_2    float64
Product_Category_3    float64
Purchase                int64
dtype: object

In [48]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
# df['Product_ID'] = label_encoder.fit_transform(df['Product_ID'])
df['City_Category'] = label_encoder.fit_transform(df['City_Category'])
# df['Stay_In_Current_City_Years'] = label_encoder.fit_transform(df['Stay_In_Current_City_Years'])
df['Product_Category_2'] = label_encoder.fit_transform(df['Product_Category_2'])
df['Product_Category_3'] = label_encoder.fit_transform(df['Product_Category_3'])

In [49]:
df.dtypes

City_Category         int32
Product_Category_1    int64
Product_Category_2    int64
Product_Category_3    int64
Purchase              int64
dtype: object

In [50]:
df.isnull().sum()

City_Category         0
Product_Category_1    0
Product_Category_2    0
Product_Category_3    0
Purchase              0
dtype: int64

In [51]:
# df['Stay_In_Current_City_Years'].unique()

In [52]:
x = df.drop('Purchase',axis=1).values
y = df['Purchase'].values

In [53]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [54]:
from sklearn.ensemble import RandomForestRegressor

In [55]:
model = RandomForestRegressor()
model = model.fit(x_train,y_train)
model

RandomForestRegressor()

In [56]:
y_predict = model.predict(x_test)
y_predict

array([ 4121.82463994, 12635.20035606, 12856.50420059, ...,
        6303.33740042, 13322.42286933,  7948.52110854])

In [57]:
from sklearn.metrics import r2_score,mean_squared_error

In [58]:
print("r2_score:", r2_score(y_test,y_predict))

r2_score: 0.6578593084317854


In [59]:
mse = mean_squared_error(y_test,y_predict)
mse

8615525.426376209

In [60]:
rmse = np.sqrt(mse)
rmse

2935.2215293528034

In [66]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [67]:
xn = scaler.fit_transform(x)
yn = scalar.fit_transform(y.reshape(-1,1))

In [70]:
yn

array([[-0.1779729 ],
       [ 1.1817558 ],
       [-1.56119326],
       ...,
       [-1.81701338],
       [-1.77162273],
       [-1.7467375 ]])

In [68]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(xn,yn,test_size=0.2)

In [69]:
model = RandomForestRegressor()
model_ss = model.fit(xtrain,ytrain)
model_ss

C:\Users\khush\AppData\Local\Temp\ipykernel_18168\2543842983.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model_ss = model.fit(xtrain,ytrain)


RandomForestRegressor()

In [71]:
y_p = model_ss.predict(xtest)
y_p

array([ 0.46061539, -0.87439646,  0.43209417, ..., -0.55082817,
       -0.37617613, -0.55078791])

In [72]:
mse_ss = mean_squared_error(ytest,y_p)
mse_ss

0.343347765616777

In [73]:
rmse_ss = np.sqrt(mse_ss)
rmse_ss

0.5859588429376051

In [74]:
r2_ss = r2_score(ytest,y_p)
r2_ss

0.658114643379396

In [82]:
kd1 = pd.read_csv("../DataSets/BFS_test.csv")
kd1

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000004  P00128942      M  46-50           7             B   
1       1000009  P00113442      M  26-35          17             C   
2       1000010  P00288442      F  36-45           1             B   
3       1000010  P00145342      F  36-45           1             B   
4       1000011  P00053842      F  26-35           1             C   
...         ...        ...    ...    ...         ...           ...   
233594  1006036  P00118942      F  26-35          15             B   
233595  1006036  P00254642      F  26-35          15             B   
233596  1006036  P00031842      F  26-35          15             B   
233597  1006037  P00124742      F  46-50           1             C   
233598  1006039  P00316642      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               1                   1   
1                               0               0                   3   
2                              4+               1                   5   
3                              4+               1                   4   
4                               1               0                   4   
...                           ...             ...                 ...   
233594                         4+               1                   8   
233595                         4+               1                   5   
233596                         4+               1                   1   
233597                         4+               0                  10   
233598                         4+               1                   4   

        Product_Category_2  Product_Category_3  
0                     11.0                 NaN  
1                      5.0                 NaN  
2                     14.0                 NaN  
3                      9.0                 NaN  
4                      5.0                12.0  
...                    ...                 ...  
233594                 NaN                 NaN  
233595                 8.0                 NaN  
233596                 5.0                12.0  
233597                16.0                 NaN  
233598                 5.0                 NaN  

[233599 rows x 11 columns]

In [83]:
columns_to_drop = ["User_ID","Product_ID","Gender","Marital_Status","Age","Stay_In_Current_City_Years",
                  "Occupation"]
kd= kd1.drop(columns=columns_to_drop)
kd

City_Category  Product_Category_1  Product_Category_2  \
0                  B                   1                11.0   
1                  C                   3                 5.0   
2                  B                   5                14.0   
3                  B                   4                 9.0   
4                  C                   4                 5.0   
...              ...                 ...                 ...   
233594             B                   8                 NaN   
233595             B                   5                 8.0   
233596             B                   1                 5.0   
233597             C                  10                16.0   
233598             B                   4                 5.0   

        Product_Category_3  
0                      NaN  
1                      NaN  
2                      NaN  
3                      NaN  
4                     12.0  
...                    ...  
233594                 NaN  
233595                 NaN  
233596                12.0  
233597                 NaN  
233598                 NaN  

[233599 rows x 4 columns]

In [84]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
kd['City_Category'] = label_encoder.fit_transform(kd['City_Category'])
kd['Product_Category_2'] = label_encoder.fit_transform(kd['Product_Category_2'])
kd['Product_Category_3'] = label_encoder.fit_transform(kd['Product_Category_3'])
# kd['Product_ID'] = label_encoder.fit_transform(kd['Product_ID'])


In [85]:
yp = model.predict(kd)
yp

C:\ProgramData\anaconda3\envs\Machinelearning\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  warnings.warn(


array([ 1.41248963,  0.2368866 , -1.77249221, ...,  1.41248963,
       -1.77249221, -1.77249221])

In [86]:
kd1['Purchase'] = yp
kd1

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000004  P00128942      M  46-50           7             B   
1       1000009  P00113442      M  26-35          17             C   
2       1000010  P00288442      F  36-45           1             B   
3       1000010  P00145342      F  36-45           1             B   
4       1000011  P00053842      F  26-35           1             C   
...         ...        ...    ...    ...         ...           ...   
233594  1006036  P00118942      F  26-35          15             B   
233595  1006036  P00254642      F  26-35          15             B   
233596  1006036  P00031842      F  26-35          15             B   
233597  1006037  P00124742      F  46-50           1             C   
233598  1006039  P00316642      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               1                   1   
1                               0               0                   3   
2                              4+               1                   5   
3                              4+               1                   4   
4                               1               0                   4   
...                           ...             ...                 ...   
233594                         4+               1                   8   
233595                         4+               1                   5   
233596                         4+               1                   1   
233597                         4+               0                  10   
233598                         4+               1                   4   

        Product_Category_2  Product_Category_3  Purchase  
0                     11.0                 NaN  1.412490  
1                      5.0                 NaN  0.236887  
2                     14.0                 NaN -1.772492  
3                      9.0                 NaN -1.772492  
4                      5.0                12.0 -1.772492  
...                    ...                 ...       ...  
233594                 NaN                 NaN -1.772492  
233595                 8.0                 NaN -1.772492  
233596                 5.0                12.0  1.412490  
233597                16.0                 NaN -1.772492  
233598                 5.0                 NaN -1.772492  

[233599 rows x 12 columns]

In [87]:
kd11 = kd1[['Purchase','User_ID','Product_ID']]

In [89]:
kd11 = kd11.set_index('Purchase')

In [90]:
kd11

User_ID Product_ID
Purchase                     
 1.412490  1000004  P00128942
 0.236887  1000009  P00113442
-1.772492  1000010  P00288442
-1.772492  1000010  P00145342
-1.772492  1000011  P00053842
...            ...        ...
-1.772492  1006036  P00118942
-1.772492  1006036  P00254642
 1.412490  1006036  P00031842
-1.772492  1006037  P00124742
-1.772492  1006039  P00316642

[233599 rows x 2 columns]

In [91]:
kd11.to_csv('BFS.csv')